const gcsPath = 'https://storage.googleapis.com/wham-uploads/defaults/'

const defaultSounds = [
    { key: 'Select a sound', value: '' },
    { key: 'Air Horn', value: `${gcsPath}airhorn.mp3` },
    { key: 'Award', value: `${gcsPath}award.mp3` },
    { key: 'Camera', value: `${gcsPath}camera.mp3` },
    { key: 'Cat', value: `${gcsPath}cat.mp3` },
    { key: 'Cha-Ching', value: `${gcsPath}cha-ching.mp3` },
    { key: 'Chicken', value: `${gcsPath}chicken.mp3` },
    { key: 'Clapping', value: `${gcsPath}clapping.mp3` },
    { key: 'Crickets', value: `${gcsPath}crickets.mp3` },
    { key: 'Crowd Laughing', value: `${gcsPath}crowd-laughing.mp3` },
    { key: 'Crowd Oooo', value: `${gcsPath}crowd-oooo.mp3` },
    { key: 'Crowd Sad', value: `${gcsPath}crowd-sad.mp3` },
    { key: 'Crowd Wow', value: `${gcsPath}crowd-wow.mp3` },
    { key: 'Crowd Yay', value: `${gcsPath}crowd-yay.mp3` },
    { key: 'Dog', value: `${gcsPath}dog.mp3` },
    { key: 'Dolphin', value: `${gcsPath}dolphin.mp3` },
    { key: 'Duck', value: `${gcsPath}duck.mp3` },
    { key: 'Error', value: `${gcsPath}error.mp3` },
    { key: 'Gasp', value: `${gcsPath}gasp.mp3` },
    { key: 'Grr', value: `${gcsPath}grr.mp3` },
    { key: 'Grunt', value: `${gcsPath}grunt.mp3` },
    { key: 'Huh', value: `${gcsPath}huh.mp3` },
    { key: 'Karate Chop', value: `${gcsPath}karate-chop.mp3` },
    { key: 'Kids Cheer', value: `${gcsPath}kids-cheer.mp3` },
    { key: 'Kids Cool', value: `${gcsPath}kids-cool.mp3` },
    { key: 'Kids Ew', value: `${gcsPath}kids-ew.mp3` },
    { key: 'Kids Wow', value: `${gcsPath}kids-wow.mp3` },
    { key: 'Magic', value: `${gcsPath}magic.mp3` },
    { key: 'Mmmm', value: `${gcsPath}mmmm.mp3` },
    { key: 'Monkey', value: `${gcsPath}monkey.mp3` },
    { key: 'Ouch', value: `${gcsPath}ouch.mp3` },
    { key: 'Yeah', value: `${gcsPath}yeah.mp3` },
    { key: 'Yee-haw', value: `${gcsPath}yeehaw.mp3` },
]

export default defaultSounds